version: "3.8"

services:
  langflow:
    image: langflow-oracle:latest
    container_name: langflow-oracle-driver
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_CONFIG_DIR=/app/data/config
      - LANGFLOW_DATABASE_URL=sqlite:///./data/database/langflow.db
      - LANGFLOW_LOG_LEVEL=INFO
    volumes:
      - ./data:/app/data
    restart: unless-stopped 